---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sj895y9980fh/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp abdullah_waseem_resume.pdf $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
